name: Update Filter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest sing-box version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r '.tag_name')
          CLEAN_VERSION=${VERSION#v}
          echo "SING_BOX_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "CLEAN_VERSION=${CLEAN_VERSION}" >> $GITHUB_ENV

      - name: Download and install sing-box
        run: |
          wget -qO sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/${SING_BOX_VERSION}/sing-box-${CLEAN_VERSION}-linux-amd64.tar.gz"
          tar -xzf sing-box.tar.gz
          chmod +x sing-box-${CLEAN_VERSION}-linux-amd64/sing-box
          sudo mv sing-box-${CLEAN_VERSION}-linux-amd64/sing-box /usr/local/bin/sing-box

      - name: Download and Convert Filter
        run: |
          curl -sSLo filter.txt "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
          sing-box rule-set convert --type adguard --output filter.srs filter.txt
          rm filter.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add filter.srs
          git commit -m "Update filter.srs on $(date -u)" || exit 0
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/FlameDancer2010/adguard-filter-storage.git
